trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - .vscode

name: $(Date:yyyy.MM.dd).$(Rev:r)

variables:
- group: common-azure-infrastructure_Production

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Dev Container Registry'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(AZURE_SERVICE_CONNECTION)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RESOURCE_GROUP_NAME)
    location: $(RESOURCE_GROUP_LOCATION)
    csmFile: './container-registry.bicep'
    overrideParameters: >
      -registryName $(ACR_REGISTRY_NAME)
      -registrySku $(ACR_REGISTRY_SKU)
    deploymentMode: 'Incremental'
    deploymentName: DeployDevelopmentACR